In [1]:
import pymysql, talib, sys, os
import pandas as pd

#################################
class General:
    conn = None
    ####################
    def __init__(self):
        if self.conn is None:
            self.conn = pymysql.connect(host='tptcn.ddns.net', port=53306, db='p_master',
                                   user=os.environ['MYSQL_READUSER'], password=os.environ['MYSQL_READPASSWORD'],
                                   cursorclass=pymysql.cursors.DictCursor)
    ####################
    def __del__(self):
        if self.conn is not None:
            self.conn.close()
            self.conn = None
            
    ####################
    def worker(self,symbol):
        tmpl = """SELECT  `Date`, `Open` , `High` , `Low` , `Close` , `Volume`
            FROM `consolidated_daily` WHERE `symbol`='%s'
            """
        sql = tmpl % (symbol)
        daily = pd.read_sql(sql, self.conn, index_col=['Date'] )

        rsi = talib.RSI( daily['Close'].values, timeperiod=14)
        daily['RSI'] = rsi
        print daily
#################################

g = General()
g.worker('0011.HK')

               Open   High    Low  Close   Volume        RSI
Date
2014-03-12  122.700  122.5  120.1  120.6  1198002        NaN
2014-03-13  120.600  121.4  119.5  120.9  1139756        NaN
2014-03-14  119.900  120.6  119.5  119.5   639054        NaN
2014-03-17  119.500  119.7  118.1  118.9  1224658        NaN
2014-03-18  119.100  119.7  118.1  118.7  1293538        NaN
2014-03-19  118.700  120.1  118.2  120.0   754484        NaN
2014-03-20  120.000  119.9  118.1  118.3  1115814        NaN
2014-03-21  118.300  119.3  118.3  118.7  1402971        NaN
2014-03-24  118.700  119.8  118.5  119.6   821757        NaN
2014-03-25  120.000  121.5  119.2  120.8  1124464        NaN
2014-03-26  120.800  122.2  121.0  121.7  1066044        NaN
2014-03-27  125.300  125.3  122.4  122.7  2228238        NaN
2014-03-28  122.700  124.0  122.1  122.7  1426898        NaN
2014-03-31  122.500  123.8  122.7  123.5  1055311        NaN
2014-04-01  124.100  124.0  123.1  124.0   876269  65.178571
2014-04-02  124.000  125.0  123.7  124.1   992159  65.510204
2014-04-03  124.100  125.0  124.4  125.0  1303611  68.424835
2014-04-04  125.000  125.5  124.8  125.5  1258756  69.944437
2014-04-07  125.500  125.5  124.0  124.9   773775  65.849007
2014-04-08  125.000  126.3  124.5  126.2  1673209  69.953978
2014-04-09  126.200  128.5  126.4  128.4  4045634  75.353201
2014-04-10  128.500  128.9  126.9  127.6  1579140  70.399116
2014-04-11  127.600  128.6  127.6  128.0  1355424  71.411190
2014-04-14  127.000  128.4  126.9  128.1  1205821  71.671955
2014-04-15  128.100  128.4  126.4  126.5   662675  61.937505
2014-04-16  126.600  127.6  125.3  125.7   872446  57.716491
2014-04-17  125.700  127.3  126.0  126.3   347953  59.922511
2014-04-22  125.700  126.4  125.3  126.0   594422  58.285126
2014-04-23  126.000  126.9  124.4  124.6  1063303  51.247516
2014-04-24  124.978  125.8  124.7  125.0   786308  52.993894
...             ...    ...    ...    ...      ...        ...
2018-11-09  182.928  182.0  176.7  177.9  4214275  28.542598
2018-11-12  177.900  179.2  176.5  178.4  1952440  29.512382
2018-11-13  177.400  179.5  175.3  179.5  2325153  31.708236
2018-11-14  181.500  181.5  177.8  178.6  1391093  30.861131
2018-11-15  179.000  180.0  176.9  179.1  1957061  31.948840
2018-11-16  179.800  181.9  178.0  180.8  2122841  35.655359
2018-11-19  180.891  181.5  178.2  179.5  2178583  34.124699
2018-11-20  179.500  179.0  176.1  176.2  2743856  30.540551
2018-11-21  175.000  177.9  174.6  177.2  2685865  32.842432
2018-11-22  176.092  178.5  176.9  177.8  1535529  34.250361
2018-11-23  178.000  178.4  177.0  177.6   718064  33.994527
2018-11-26  177.563  181.2  178.0  180.5  2617022  40.889186
2018-11-27  180.500  180.9  178.6  180.0  2504562  40.111229
2018-11-28  179.975  182.3  179.5  181.8  1854412  44.225297
2018-11-29  182.271  183.4  180.0  180.1  1866555  41.337098
2018-11-30  182.492  182.1  179.5  180.6  4126939  42.525966
2018-12-03  180.600  184.0  181.9  183.8  3624455  49.570035
2018-12-04  183.800  187.3  183.0  187.2  2372810  55.772420
2018-12-05  187.200  184.5  182.3  183.2  1944245  48.253363
2018-12-06  180.800  181.5  179.0  180.1  2774092  43.373024
2018-12-07  179.100  183.9  180.4  181.0  1756742  45.108788
2018-12-10  181.000  180.0  176.4  177.0  2221132  39.337459
2018-12-11  177.112  177.8  176.3  176.3  1496852  38.411277
2018-12-12  178.000  178.8  176.8  177.3  1681210  40.564182
2018-12-13  178.900  179.8  178.3  179.4  1686782  44.918622
2018-12-14  179.568  178.8  177.0  178.2  1171536  42.980837
2018-12-17  178.200  179.4  177.6  177.8  1009209  42.325381
2018-12-18  178.024  179.0  176.5  177.0  1464492  40.979370
2018-12-19  177.000  178.2  176.0  176.0  1084208  39.297074
2018-12-20  175.300  176.7  174.0  174.2  2181744  36.400393

[1152 rows x 6 columns]